site_name: Plumbers' Friday
site_url: https://electronicnomad.net/pf/
site_author: Kwanghoon Jhin
site_description: unofficial manual and/or commentary on IT technologies.
#
repo_name: electronicnomad/plumbers-friday
repo_url: https://github.com/electronicnomad/plumbers-friday
#
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Noto Sans KR
    code: Noto Mono
  logo: logo-plumping-white.png
  favicon: favicon-plumping-black.ico
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
#
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
  - redirects:
      redirect_maps:
         'forecast/index.md': 'aws/forecast/index.md'
         'networking/index.md': 'aws/networking/index.md'
  - include-markdown
#
markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_truly_sane_lists
#
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/electronicnomad
    - icon: fontawesome/brands/blogger
      link: https://www.jhin.com
  analytics:
    provider: google
    property: UA-113185952-3
    #property: G-288189520
#
