site_name: Plumbers' Friday
site_url: https://electronicnomad.net/pf/
site_author: Kwanghoon Jhin
site_description: unofficial manual and/or commentary on IT technologies.
#
repo_name: electronicnomad/plumbers-friday
repo_url: https://github.com/electronicnomad/plumbers-friday
#
theme:
  name: material
  palette:
    primary: black
    accent: blue
  font:
    text: Noto Sans KR
    code: Noto Mono
  logo: images/logo-plumping-white.png
  favicon: images/favicon-plumping-black.ico
#
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_truly_sane_lists
#
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/electronicnomad
    - icon: fontawesome/brands/blogger
      link: https://www.jhin.com
#
google_analytics:
  - UA-113185952-3
  - auto
