site_name: a hitchhiker's unofficial guide to the AWS
theme:
  name: material
  palette:
    primary: black
    accent: deep orange
  font:
    text: Noto Sans
    code: Noto Sans Mono
  logo: images/cloud-circle-white.png
  favicon: images/favicon-cloud-black.ico
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - toc:
      permalink: true
repo_name: electronicnomad/plumbers-friday
repo_url: https://github.com/electronicnomad/plumbers-friday
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/electronicnomad
    - icon: fontawesome/brands/blogger
      link: https://www.jhin.com
# Google Analytics
google_analytics:
  - UA-113185952-3
  - auto
